server:
  port: 8094    #port where this microservice will run
 
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/ #eureka endpoint
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:     
  application:
    name: subject   #service name, this will appear in eureka server homepage
  config:
    import: optional:configserver:http://localhost:8888/
     
management.endpoints.web.exposure.include: health,info,refresh

