server:
  port: 8093    #port where this microservice will run
 
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/ #eureka endpoint
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:     
  application:
    name: student   #service name, this will appear in eureka server homepage
     
management:
  security:
    enabled: false  
 
